name: 'Create PreRelease-Build'

on:
  push:
    branches: [ 'master' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Fetch Onkostar-API
        run: |
          curl -L --user dnpm:${{ secrets.PACKAGE_TOKEN }} \
            https://git.dnpm.dev/api/packages/Plugin-JF-Onkostar/generic/onkostar-api/2.14.2/onkostar-api-2.14.2.jar \
            --output ${{ github.workspace }}/libs/onkostar-api-2.14.2.jar

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew shadowJar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: PreRelease-Build_${{ github.run_number }}
          prerelease: 'true'
          draft: 'true'
          make_latest: 'true'
          generate_release_notes: 'true'
          files: |
            build/libs/*.jar